#
# For more info check out:
# https://gitlab.corp.redhat.com/infosec-public/developer-workbench/guides/-/blob/main/project-gitlab-ci.md
#
default:
  image: "$BUILD_ENV_IMAGE"

Run Tests:
  stage: test
  script:
    - make clean setup test
